"""Codebase Guide storage and deterministic reads (T15, FR43, D18).

No MCP/HTTP imports. Summaries are caller-supplied only (INV-GUIDE-1). Indexed
facts come from active non-skipped files and resolved edges (INV-GUIDE-2). Notes
key by ``(project_id, path)`` so full reindex cannot drop prose (INV-GUIDE-3).
"""

from __future__ import annotations

import inspect
import logging
import re
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from datetime import UTC, datetime
from difflib import get_close_matches
from pathlib import Path
from typing import Final

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from pcs.codemap.service import CodeMapError
from pcs.config import get_settings
from pcs.context.service import resolve_project
from pcs.context.types import CONTRACT_AUTHOR_MAX_CHARS, ValidationError
from pcs.index.models import IndexStatus
from pcs.index.schema import ensure_index_schema
from pcs.repofile import atomic_write, dir_writable, resolve_configured_path

logger = logging.getLogger("pcs")

INCLUDE_ALL: Final = "all"
INCLUDE_DOCUMENTED: Final = "documented"
INCLUDE_UNDOCUMENTED: Final = "undocumented"
INCLUDE_STALE: Final = "stale"
INCLUDE_MODES: Final = frozenset(
    {INCLUDE_ALL, INCLUDE_DOCUMENTED, INCLUDE_UNDOCUMENTED, INCLUDE_STALE}
)
NEAR_MATCH_LIMIT: Final = 5
SUMMARY_MAX_CHARS: Final = 8000
DO_NOT_EDIT: Final = "<!-- Do not edit: generated by PCS from agent-authored notes. -->"

_SECRET_RE = re.compile(
    r"(password|secret|api[_-]?key|token|bearer|private[_-]?key)\s*[:=]",
    re.IGNORECASE,
)
_DIFF_MARKERS: Final[tuple[str, ...]] = ("diff --git", "\n+++ ", "\n--- ", "\n@@ ")
_LOG_MARKERS: Final[tuple[str, ...]] = ("traceback (most recent", "stdout", "stderr")


@dataclass(frozen=True)
class _IndexedFile:
    path: str
    language: str | None
    loc: int
    content_hash: str
    skipped: bool
    skip_reason: str | None


def _bound_author(author: str) -> str:
    cleaned = author.strip()
    if not cleaned:
        raise ValidationError("author must not be empty")
    if len(cleaned) > CONTRACT_AUTHOR_MAX_CHARS:
        raise ValidationError(f"author must be at most {CONTRACT_AUTHOR_MAX_CHARS} characters")
    return cleaned


def _bound_summary(summary: str) -> str:
    """Reject logs, diffs, secrets, and oversized prose (INV-GUIDE-1 privacy bound)."""
    cleaned = summary.strip()
    if not cleaned:
        return ""
    lower = cleaned.lower()
    if len(cleaned) > SUMMARY_MAX_CHARS:
        raise ValidationError(f"summary exceeds {SUMMARY_MAX_CHARS} characters")
    if _SECRET_RE.search(cleaned):
        raise ValidationError("summary looks like a secret")
    if any(marker in cleaned for marker in _DIFF_MARKERS) or any(
        marker in lower for marker in _LOG_MARKERS
    ):
        raise ValidationError("summary looks like a log or diff")
    return cleaned


def _normalize_path(path: str) -> str:
    cleaned = path.strip().strip("/").replace("\\", "/")
    if not cleaned:
        raise ValidationError("path must not be empty")
    parts = cleaned.split("/")
    if any(p in ("", ".", "..") for p in parts):
        raise ValidationError(f"invalid path {path!r}")
    if path.strip().startswith("/"):
        raise ValidationError(f"path must be repository-relative: {path!r}")
    return "/".join(parts)


def _normalize_scope(scope: str | None) -> str:
    """Repo-relative scope; invalid values raise ``CodeMapError`` like the code map."""
    if scope is None:
        return ""
    cleaned = scope.strip().strip("/").replace("\\", "/")
    if not cleaned:
        return ""
    parts = cleaned.split("/")
    if any(p in ("", ".", "..") for p in parts):
        raise CodeMapError(f"invalid scope {scope!r}")
    return "/".join(parts)


def _validate_include(include: str) -> str:
    mode = include.strip().lower()
    if mode not in INCLUDE_MODES:
        raise ValidationError(f"include must be one of {sorted(INCLUDE_MODES)}; got {include!r}")
    return mode


def _group_key(path: str) -> str:
    return path.split("/", 1)[0] if "/" in path else "."


async def _load_indexed(session: AsyncSession, pid: str) -> dict[str, _IndexedFile]:
    rows = await session.execute(
        text(
            """
            SELECT f.path, f.language, f.content_hash, f.skipped, f.skip_reason,
                   COALESCE(MAX(c.end_line), 0) AS loc
            FROM code_index.files f
            LEFT JOIN code_index.chunks c
              ON c.project_id = f.project_id AND c.file_id = f.id
            WHERE f.project_id = :pid
            GROUP BY f.path, f.language, f.content_hash, f.skipped, f.skip_reason
            ORDER BY f.path
            """
        ),
        {"pid": pid},
    )
    out: dict[str, _IndexedFile] = {}
    for row in rows:
        out[str(row.path)] = _IndexedFile(
            path=str(row.path),
            language=str(row.language) if row.language is not None else None,
            loc=int(row.loc or 0),
            content_hash=str(row.content_hash or ""),
            skipped=bool(row.skipped),
            skip_reason=str(row.skip_reason) if row.skip_reason is not None else None,
        )
    return out


def _active(files: Mapping[str, _IndexedFile]) -> dict[str, _IndexedFile]:
    return {path: row for path, row in files.items() if not row.skipped}


async def _load_notes(session: AsyncSession, pid: str) -> dict[str, dict[str, object]]:
    rows = await session.execute(
        text(
            """
            SELECT path, summary, content_hash, updated_by, updated_at
            FROM code_index.file_notes
            WHERE project_id = :pid
            """
        ),
        {"pid": pid},
    )
    notes: dict[str, dict[str, object]] = {}
    for row in rows:
        notes[str(row.path)] = {
            "summary": str(row.summary),
            "content_hash": str(row.content_hash),
            "updated_by": str(row.updated_by),
            "updated_at": row.updated_at.isoformat() if row.updated_at is not None else None,
        }
    return notes


async def _load_symbols(session: AsyncSession, pid: str) -> dict[str, list[str]]:
    rows = await session.execute(
        text(
            """
            SELECT path, name FROM code_index.symbols
            WHERE project_id = :pid
            ORDER BY path, start_line, name
            """
        ),
        {"pid": pid},
    )
    symbols: dict[str, list[str]] = {}
    for row in rows:
        symbols.setdefault(str(row.path), []).append(str(row.name))
    return symbols


async def _load_connections(
    session: AsyncSession, pid: str
) -> tuple[dict[str, list[str]], dict[str, list[str]]]:
    """Resolved import edges whose endpoints are both active (INV-GUIDE-2)."""
    rows = await session.execute(
        text(
            """
            SELECT e.src_path, e.dst_path
            FROM code_index.symbol_edges e
            INNER JOIN code_index.files src
              ON src.project_id = e.project_id
             AND src.path = e.src_path
             AND src.skipped = false
            INNER JOIN code_index.files dst
              ON dst.project_id = e.project_id
             AND dst.path = e.dst_path
             AND dst.skipped = false
            WHERE e.project_id = :pid AND e.dst_path <> ''
            """
        ),
        {"pid": pid},
    )
    imports: dict[str, set[str]] = {}
    importers: dict[str, set[str]] = {}
    for row in rows:
        src = str(row.src_path)
        dst = str(row.dst_path)
        imports.setdefault(src, set()).add(dst)
        importers.setdefault(dst, set()).add(src)
    return (
        {path: sorted(values) for path, values in imports.items()},
        {path: sorted(values) for path, values in importers.items()},
    )


async def _coverage(
    session: AsyncSession, pid: str, active: Mapping[str, _IndexedFile]
) -> dict[str, int]:
    notes = await _load_notes(session, pid)
    documented = 0
    stale = 0
    for path, file_row in active.items():
        note = notes.get(path)
        if note is None:
            continue
        documented += 1
        if str(note["content_hash"]) != file_row.content_hash:
            stale += 1
    return {"documented": documented, "total": len(active), "stale": stale}


async def _provenance(session: AsyncSession, pid: str) -> dict[str, object]:
    status = await session.get(IndexStatus, pid)
    if status is None:
        return {"indexed": False}
    return {
        "indexed": status.last_full_at is not None,
        "last_full_at": status.last_full_at.isoformat() if status.last_full_at else None,
        "last_incremental_at": (
            status.last_incremental_at.isoformat() if status.last_incremental_at else None
        ),
        "last_commit": status.last_commit,
        "source": "code_index",
    }


def _file_payload(
    file_row: _IndexedFile,
    note: Mapping[str, object] | None,
    symbols: Sequence[str],
    imports: Sequence[str],
    imported_by: Sequence[str],
) -> dict[str, object]:
    stale = False
    summary_meta: dict[str, object] | None = None
    if note is not None:
        stale = str(note["content_hash"]) != file_row.content_hash
        summary_meta = {
            "summary": note["summary"],
            "updated_by": note["updated_by"],
            "updated_at": note["updated_at"],
            "content_hash": note["content_hash"],
        }
    return {
        "path": file_row.path,
        "language": file_row.language,
        "loc": file_row.loc,
        "symbols": list(symbols),
        "imports": list(imports),
        "imported_by": list(imported_by),
        "summary": None if note is None else note["summary"],
        "note": summary_meta,
        "stale": stale,
    }


async def get_codebase_guide(
    session: AsyncSession,
    *,
    project: str,
    scope: str | None = None,
    include: str = INCLUDE_ALL,
) -> dict[str, object]:
    """Scoped guide rows plus coverage and index provenance (INV-GUIDE-2, INV-GUIDE-4)."""
    row = await resolve_project(session, project)
    await ensure_index_schema(session)
    mode = _validate_include(include)
    scope_norm = _normalize_scope(scope)
    indexed = await _load_indexed(session, row.id)
    active = _active(indexed)
    scoped = {
        path: file_row
        for path, file_row in active.items()
        if scope_norm == "" or path == scope_norm or path.startswith(scope_norm + "/")
    }
    if scope_norm and not scoped:
        raise CodeMapError(f"scope {scope_norm!r} has no indexed files in project {row.name!r}")
    notes = await _load_notes(session, row.id)
    symbols = await _load_symbols(session, row.id)
    imports, importers = await _load_connections(session, row.id)
    files: list[dict[str, object]] = []
    for path in sorted(scoped):
        file_row = scoped[path]
        note = notes.get(path)
        stale = note is not None and str(note["content_hash"]) != file_row.content_hash
        documented = note is not None
        if mode == INCLUDE_DOCUMENTED and not documented:
            continue
        if mode == INCLUDE_UNDOCUMENTED and documented:
            continue
        if mode == INCLUDE_STALE and not stale:
            continue
        files.append(
            _file_payload(
                file_row,
                note,
                symbols.get(path, []),
                imports.get(path, []),
                importers.get(path, []),
            )
        )
    return {
        "project": row.name,
        "scope": scope_norm or None,
        "include": mode,
        "coverage": await _coverage(session, row.id, active),
        "generated_from": await _provenance(session, row.id),
        "files": files,
    }


async def describe_files(
    session: AsyncSession,
    *,
    project: str,
    notes: Sequence[Mapping[str, object]],
    author: str,
    write_artifact: bool = True,
) -> dict[str, object]:
    """Upsert or delete caller-supplied summaries (INV-GUIDE-1, INV-GUIDE-6)."""
    row = await resolve_project(session, project)
    await ensure_index_schema(session)
    who = _bound_author(author)
    if not notes:
        raise ValidationError("notes must not be empty")
    indexed = await _load_indexed(session, row.id)
    active = _active(indexed)
    active_paths = sorted(active)
    seen: set[str] = set()
    prepared: list[tuple[str, str]] = []
    for item in notes:
        raw_path = item.get("path")
        raw_summary = item.get("summary")
        if not isinstance(raw_path, str):
            raise ValidationError("each note requires a string path")
        if not isinstance(raw_summary, str):
            raise ValidationError("each note requires a string summary")
        path = _normalize_path(raw_path)
        if path in seen:
            raise ValidationError(f"duplicate path {path!r}")
        seen.add(path)
        prepared.append((path, _bound_summary(raw_summary)))

    unknown: list[dict[str, object]] = []
    applied: list[str] = []
    deleted: list[str] = []
    now = datetime.now(UTC)
    for path, summary in prepared:
        file_row = indexed.get(path)
        if file_row is None or file_row.skipped:
            reason = "skipped" if file_row is not None and file_row.skipped else "unknown"
            unknown.append(
                {
                    "path": path,
                    "reason": reason,
                    "near": get_close_matches(path, active_paths, n=NEAR_MATCH_LIMIT, cutoff=0.4),
                }
            )
            continue
        if summary == "":
            await session.execute(
                text("DELETE FROM code_index.file_notes WHERE project_id = :pid AND path = :path"),
                {"pid": row.id, "path": path},
            )
            deleted.append(path)
            continue
        await session.execute(
            text(
                """
                INSERT INTO code_index.file_notes
                    (project_id, path, summary, content_hash, updated_by, updated_at)
                VALUES
                    (:pid, :path, :summary, :hash, :author, :updated_at)
                ON CONFLICT (project_id, path) DO UPDATE SET
                    summary = EXCLUDED.summary,
                    content_hash = EXCLUDED.content_hash,
                    updated_by = EXCLUDED.updated_by,
                    updated_at = EXCLUDED.updated_at
                """
            ),
            {
                "pid": row.id,
                "path": path,
                "summary": summary,
                "hash": file_row.content_hash,
                "author": who,
                "updated_at": now,
            },
        )
        applied.append(path)

    if not applied and not deleted:
        raise ValidationError("no valid indexed paths in notes")

    await session.flush()
    coverage = await _coverage(session, row.id, active)
    artifact: dict[str, object] = {"path": None, "file_writable": False, "error": None}
    if write_artifact:
        artifact = await write_guide_file(session, project=project)
    return {
        "applied": applied,
        "deleted": deleted,
        "unknown": unknown,
        "coverage": coverage,
        "file_writable": artifact["file_writable"],
        "artifact": artifact,
    }


def render_guide_markdown(guide: Mapping[str, object]) -> str:
    """Deterministic Markdown grouped by top-level directory (INV-GUIDE-1)."""
    coverage = guide["coverage"]
    assert isinstance(coverage, Mapping)
    lines = [
        "# Codebase Guide",
        "",
        DO_NOT_EDIT,
        "",
        (
            f"Coverage: documented {coverage['documented']} / total {coverage['total']}"
            f" · stale {coverage['stale']}"
        ),
        "",
    ]
    raw_files = guide.get("files")
    files: list[Mapping[str, object]] = []
    if isinstance(raw_files, Sequence) and not isinstance(raw_files, (str, bytes)):
        for raw in raw_files:
            if isinstance(raw, Mapping):
                files.append(raw)
    groups: dict[str, list[Mapping[str, object]]] = {}
    for raw in files:
        path = str(raw["path"])
        groups.setdefault(_group_key(path), []).append(raw)
    for top in sorted(groups):
        lines.append(f"## {top}")
        lines.append("")
        for file_row in sorted(groups[top], key=lambda item: str(item["path"])):
            path = str(file_row["path"])
            lines.append(f"### {path}")
            lines.append("")
            summary = file_row.get("summary")
            if isinstance(summary, str) and summary:
                lines.append(summary.rstrip())
                lines.append("")
            else:
                lines.append("_Undocumented._")
                lines.append("")
            if file_row.get("stale"):
                lines.append("_Stale: indexed content hash differs from the captured note hash._")
                lines.append("")
            raw_imports = file_row.get("imports")
            raw_imported = file_row.get("imported_by")
            imports = (
                [str(item) for item in raw_imports]
                if isinstance(raw_imports, Sequence) and not isinstance(raw_imports, (str, bytes))
                else []
            )
            imported_by = (
                [str(item) for item in raw_imported]
                if isinstance(raw_imported, Sequence) and not isinstance(raw_imported, (str, bytes))
                else []
            )
            if imports:
                lines.append("Imports: " + ", ".join(imports))
                lines.append("")
            if imported_by:
                lines.append("Imported by: " + ", ".join(imported_by))
                lines.append("")
    return "\n".join(lines).rstrip() + "\n"


async def write_guide_file(
    session: AsyncSession,
    *,
    project: str,
) -> dict[str, object]:
    """Atomically replace the configured guide file; never raises for I/O (INV-GUIDE-5/6)."""
    row = await resolve_project(session, project)
    guide = await get_codebase_guide(session, project=project, include=INCLUDE_ALL)
    markdown = render_guide_markdown(guide)
    try:
        target = resolve_configured_path(row.root_path, get_settings().codebase_guide_file)
    except ValueError as exc:
        logger.info(
            "codebase_guide_path_rejected", extra={"context": {"error": type(exc).__name__}}
        )
        return {"path": None, "file_writable": False, "error": "path-rejected"}
    parent = target.parent
    if not parent.exists():
        try:
            parent.mkdir(parents=True, exist_ok=True)
        except OSError:
            return {"path": str(target), "file_writable": False, "error": "not-writable"}
    if not dir_writable(parent):
        return {"path": str(target), "file_writable": False, "error": "not-writable"}
    # Relative guide settings must stay under the project root for the whole
    # atomic write; absolute settings follow the requirements-file policy.
    setting = get_settings().codebase_guide_file.strip()
    contain_under = (
        None if Path(setting).is_absolute() else Path(row.root_path).expanduser().resolve()
    )
    try:
        atomic_write(target, markdown, contain_under=contain_under)
    except ValueError:
        logger.info("codebase_guide_write_failed", extra={"context": {"error": "path-rejected"}})
        return {"path": str(target), "file_writable": False, "error": "path-rejected"}
    except OSError:
        logger.info("codebase_guide_write_failed", extra={"context": {"error": "oserror"}})
        return {"path": str(target), "file_writable": False, "error": "write-failed"}
    return {"path": str(target), "file_writable": True, "error": None}


def automatic_summary_generation_exists() -> bool:
    """False: T15 has no stub or LLM summary path (INV-GUIDE-1 / AC-GUIDE-1)."""
    source = inspect.getsource(describe_files) + inspect.getsource(get_codebase_guide)
    banned = ("openai", "chat/completions", "llm", "generate_summary", "auto_stub")
    return any(token in source.lower() for token in banned)
